export const doctors = [
  
  {
    id: 1,
    name: "Dr. K. VELUSWAMY",
    qualification: "M.D(Med), (A.I.I.M.S), F.C.C.P, M.Sc.(Repro.Med.), P.G.(Dip), U.S.G",
    designation: "Founder & Senior Consultant Cardiologist",
    specialization: "Cardiology & General Medicine",
    experience: "40+ Years",
    experienceYears: 40,
    isActive: true,
    showSpecialization: true,

    bio: "Dr. K. Veluswamy is the Founder and Owner of the Hospital and a highly experienced Senior Consultant Cardiologist with over 40 years of distinguished experience in clinical medicine. With extensive expertise in cardiology, general medicine, comprehensive diagnosis, critical care, and preventive healthcare, he is committed to delivering trusted, personalized, and evidence-based medical care. His four decades of experience, leadership, and patient-first approach have made him a respected name in healthcare.",

    specialistIn: [
      "Cardiology & Heart Care",
      "General Medicine",
      "Comprehensive Medical Diagnosis",
      "Critical & Emergency Medical Care",
      "Preventive Healthcare",
      "Cardiovascular Disease Management",
      "Hypertension Management",
      "Diabetes & Metabolic Care",
      "Lifestyle Disease Management",
      "Comprehensive Health Assessment",
      "Specialized Medical Consultation",
      "Multi-Specialty Medical Care",
    ],

    highlights: [
      "40+ Years of Medical Experience",
      "Founder & Owner of the Hospital",
      "Senior Consultant Cardiologist",
      "Extensive Clinical Expertise",
      "Patient-Centered Approach",
      "Comprehensive Medical Care",
    ],

    image: "/images/doctors/doctor1.jpg",
  },

  {
    id: 2,
    name: "Dr. ANAND",
    qualification: "MBBS., MD (GEN MED)",
    specialization: "General Physician",
    experience: "8+ Years",
    experienceYears: 8,
    isActive: true,
    showSpecialization: true,
    bio: "An experienced General Physician committed to delivering comprehensive, evidence-based, and patient-centered medical care. With a strong focus on accurate diagnosis, timely treatment, preventive healthcare, and effective management of acute and chronic medical conditions, dedicated to providing dependable medical support. Experienced in emergency and critical care, with an emphasis on clear communication, compassionate treatment, and personalized healthcare for patients of all age groups.",
    specialistIn: [
      "General Medicine",
      "Cardiology Treatments",
      "ICU & Emergency Medical Care",
      "Poisoning Treatment",
      "Nephrology Care",
      "Gastroenterology Care",
      "Orthopedic Care",
      "Stroke Care",
      "Breast Specialty Care", 
      "Diabetes Management",
      "Hypertension Management",
      "Preventive Healthcare",
    ],
    image: "/images/doctors/doctor2.jpg",
  },

  {
    id: 3,
    name: "Dr. UTHAYA KUMAR",
    qualification: "MBBS., M.S (GENERAL SURGEON)",
    specialization: "General Surgeon",
    experience: "3+ Years",
    experienceYears: 3,
    isActive: true,
    showSpecialization: true,
    bio: "Dedicated general surgeon providing careful evaluation and surgical care with a strong focus on patient safety, recovery, and personalized treatment.",
    specialistIn: [
      "General Surgery",
      "Surgical Consultation",
      "Proctoscopy",
      "Laparoscopic Surgery",
      "Major & Minor Surgical Procedures",
      "Post-Surgical Care",
      "Diabetic Foot Care",
      "Wound Surgery & Wound Infection Management",
    ],
    image: "/images/doctors/doctor3.jpg",
  },

  {
    id: 4,
    name: "Dr. SRINATH",
    qualification: "MBBS",
    specialization: "Duty Doctor",
    experience: "3+ Years",
    experienceYears: 3,
    isActive: true,
    showSpecialization: true,
    bio: "Committed to providing responsive medical care, initial assessment, and continuous patient support with a patient-first approach.",
    specialistIn: [
      "General Consultation",
      "Resident Medical Officer (RMO)",
      "Initial Assessment",
      "Emergency Support",
      "Patient Monitoring",
    ],
    image: "/images/doctors/doctor4.jpg",
  },

  {
    id: 5,
    name: "Dr. MANOJ KUMAR",
    qualification: "MBBS",
    specialization: "Duty Doctor",
    experience: "3+ Years",
    experienceYears: 3,
    isActive: true,
    showSpecialization: true,
    bio: "An experienced duty doctor focused on timely medical assessment, patient monitoring, and coordinated care for a wide range of healthcare needs.",
    specialistIn: [
      "General Consultation",
      "Resident Medical Officer (RMO)",
      "Patient Monitoring",
      "Emergency Support",
      "Primary Care",
    ],
    image: "/images/doctors/doctor5.jpg",
  },

  {
    id: 6,
    name: "Dr. REEN",
    qualification: "MBBS",
    specialization: "Duty Doctor",
    experience: "3+ Years",
    experienceYears: 3,
    isActive: false,
    showSpecialization: true,
    bio: "An experienced duty doctor focused on timely medical assessment, patient monitoring, and coordinated care for a wide range of healthcare needs.",
    specialistIn: [
      "General Consultation",
      "Resident Medical Officer (RMO)",
      "Patient Monitoring",
      "Emergency Support",
      "Primary Care",
    ],
    image: "/images/doctors/doctor6.jpg",
  },
];