export const doctors = [
  {
    id: 1,
    name: "Dr. ANAND",
    qualification: "MBBS., MD (GEN MED)",
    specialization: "General Physician",
    experience: "8+ Years",
    experienceYears: 8,
    isActive: true,
    bio: "Experienced general physician focused on accurate diagnosis, preventive healthcare, and compassionate treatment for patients of all age groups.",
    specialistIn: [
      "General Medicine",
      "Diabetes Management",
      "Hypertension Care",
      "Preventive Healthcare",
    ],
    image: "/images/doctors/doctor1.jpg",
  },

  {
    id: 2,
    name: "Dr. UTHAYA KUMAR",
    qualification: "MBBS., M.S (GENERAL SURGEON)",
    specialization: "General Surgeon",
    experience: "2+ Years",
    experienceYears: 2,
    isActive: true,
    bio: "Dedicated general surgeon providing careful evaluation and surgical care with a strong focus on patient safety, recovery, and personalized treatment.",
    specialistIn: [
      "General Surgery",
      "Surgical Consultation",
      "Minor Procedures",
      "Post-Surgical Care",
    ],
    image: "/images/doctors/doctor2.jpg",
  },

  {
    id: 3,
    name: "Dr. SRINATH",
    qualification: "MBBS",
    specialization: "Duty Doctor",
    experience: "2 Years",
    experienceYears: 2,
    isActive: true,
    bio: "Committed to providing responsive medical care, initial assessment, and continuous patient support with a patient-first approach.",
    specialistIn: [
      "General Consultation",
      "Initial Assessment",
      "Emergency Support",
      "Patient Monitoring",
    ],
    image: "/images/doctors/doctor3.jpg",
  },

  {
    id: 4,
    name: "Dr. MANOJ KUMAR",
    qualification: "MBBS",
    specialization: "Duty Doctor",
    experience: "10+ Years",
    experienceYears: 10,
    isActive: true,
    bio: "An experienced duty doctor focused on timely medical assessment, patient monitoring, and coordinated care for a wide range of healthcare needs.",
    specialistIn: [
      "General Consultation",
      "Patient Monitoring",
      "Emergency Support",
      "Primary Care",
    ],
    image: "/images/doctors/doctor4.jpg",
  },

  {
    id: 5,
    name: "Dr. WAITING",
    qualification: "MBBS",
    specialization: "Duty Doctor",
    experience: "10+ Years",
    experienceYears: 10,
    isActive: false,
    bio: "An experienced duty doctor focused on timely medical assessment, patient monitoring, and coordinated care for a wide range of healthcare needs.",
    specialistIn: [
      "General Consultation",
      "Patient Monitoring",
      "Emergency Support",
      "Primary Care",
    ],
    image: "/images/doctors/doctor5.jpg",
  },
];